### ISSUE TITLE
5.13.0 and 5.14.2.1 are the same file

### ISSUE THREAD

**Issue by okletzmayr** [acbetter/qt-for-python-to-dash-docset#2]
Hey, sorry to bother you again.
I compared my locally generated docset with the one you added to Dash User Contributions.
5.13.0 and 5.14.2.1 are the same file.

```
> shasum versions/5.13.0/Qt_for_Python.tgz; shasum versions/5.14.2.1/Qt_for_Python.tgz
a31b5eb7696f0225b746ae3423bd8b046a3c2593  versions/5.13.0/Qt_for_Python.tgz
a31b5eb7696f0225b746ae3423bd8b046a3c2593  versions/5.14.2.1/Qt_for_Python.tgz
```

I pushed the new packed docset to my fork in case you want to use it. https://github.com/okletzmayr/qt-for-python-to-dash-docset/commit/143ed678f6d6006caa7e0ac953becfc0d63a0579
And thanks for the super fast response to my last pull request, I appreciate it.

**Comment by acbetter** [comment]
I am indeed very sorry that I missed the checksums between docset versions and late response.

I will update Dash User Contributions later.

**Comment by okletzmayr** [comment]
No worries. At this point we might as well wait for the 5.15 Release, which is [scheduled](https://wiki.qt.io/Qt_5.15_Release) for next week. You could push both 5.15 as an update, and this 5.14.2 version for legacy reasons next week. I'll generate the 5.15 docset for myself anyways; I could open a pull request again.

**Comment by acbetter** [comment]
closed by https://github.com/Kapeli/Dash-User-Contributions/pull/2794
