### ISSUE TITLE
How much time will be consumed to run the python script until the end

### ISSUE THREAD

**Issue by TangChiaHsin** [acbetter/qt-for-python-to-dash-docset#7]
I can not run `pyside2dash.py` directly on macOS when the version of PySide6 == 6.4. and there's the wget command to download the source file.
```wget --execute robots=off --wait=0.5 --force-directories --no-parent --page-requisites --mirror --convert-links --tries=3 https://doc.qt.io/qtforpython-6/```
The directory size is 785.2 MegaBytes. All required python libraries have been installed. And the problem arises in the function `get_function(classes: list)` of the script (lines 73), no result has been found by `soup = soup.find("div", class_="body")`. I change it  to `soup = soup.find("body")`. The script runs successfully.

However, the length of the list "classes" exceeds 3000000, which makes the time consumption of running the script unacceptable.

I don't know much about BeautifulSoup and HTML, so I'd like to ask
(1) if it's my changes or the website source file changes that are causing this?
(2) How long did it take you to run the script?

**Comment by acbetter** [comment]
My script may have bugs these days because the original https://doc.qt.io/qtforpython-6/ website changes. I'm sorry for that because I didn't use macOS anymore... Hope someone fix/fork or pull request

**Comment by TangChiaHsin** [comment]
> My script may have bugs these days because the original https://doc.qt.io/qtforpython-6/ website changes. I'm sorry for that because I didn't use macOS anymore... Hope someone fix/fork or pull request

Thanks for your reply and I will try to fix it. if the script successfully runs, I will initiate a pull request.
