### ISSUE TITLE
Bug: text size constantly changing, smooth scrolling, selected item not visible after layout stops transitioning

### ISSUE THREAD

**Issue by gingerbeardman** [acbetter/qt-for-python-to-dash-docset#9]
Thanks for this useful doc set!

I see some very odd behaviour which could be related to CSS transitions or JavaScript?

The text size constantly changes and there seems to be some sort of smooth scroll happening?
This means that it takes a while for the selected item to come into view, and more often than not after the text resizing the selected item is not on screen so I have to search for it a second time to make it appear on screen.

I think static text size and no smooth scrolling would be preferable.

Also, I've not seen any other docsets where this happens.

## Screen recording
https://github.com/user-attachments/assets/0b6db5e3-2745-46f6-96f3-c1328b415b40

**Comment by acbetter** [comment]
This issue has been present since the first version. The project only crawls the entire website and creates the corresponding dash index for easy navigation. During this process, no modifications are made to the source web pages. Therefore, when you open a page, the JavaScript scripts and CSS animations from the source web pages will run again, which may cause some discomfort.

**Comment by acbetter** [comment]
Update: The official website [Qt for Python](https://doc.qt.io/qtforpython-6/index.html) has been updated to a new CSS style, but this project is adapted to the old style. This means that the project cannot function correctly at this stage.

**Comment by gingerbeardman** [comment]
Thanks, that explains it.

I notice that there is a PR to update the project to the new format. Hopefully that can be merged soon and new docset issues. Cheers!

**Comment by gingerbeardman** [comment]
Thanks for merging the PR.

Is there an additional process required to make an new/updated new docset appear in Dash app?
